# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://std003-internal.softium.cn:3306/batch-test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456@TM
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#  sql:
#    init:
#      schema-locations: classpath:sample-data.sql
#      data-locations: classpath:db/data-h2.sql
